### PR TITLE
prevent coupon to be applied if expired

### PR DESCRIPTION
**Pull request by Zelig880**
Prevent a coupon from being applied even if it has already expired, or if the card date time is not aligned with the expeted day and time of its order.

relates #18

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Thanks for the PR.
I've refactored to make use of the logic already in place for validating the coupon - let me know what you think

**Comment by sampoyigi** [comment]
@ryanmitchell There's a difference in how CartConditions is applied to the Cart and CartItem.. `beforeApply` is only called when applying on the entire cart so @Zelig880 approach should be fine.

**Comment by ryanmitchell** [comment]
It works in one sense - as in it stops the reported issue, but it doesnt check all the validity conditions (recurring, min totals etc)... without this change those are never checked on cart item only coupons.

**Comment by sampoyigi** [comment]
By design, cart condition rules are only validated when it's being applied on the entire cart, we let developers validate the cart item conditions before it's applied to the item. So it makes sense to do the check before applying the condition to the cart item.. What we can do is move the validation logic into the CartManager so we can call it from the cart condition and also before applying to items.

**Comment by sampoyigi** [comment]
@ryanmitchell what are your thoughts? 

Related: https://github.com/tastyigniter/ti-ext-coupons/pull/20

**Comment by ryanmitchell** [comment]
Sorry, missed your initial reply. Yep this sounds good, making it more accessible to conditions can opt in to using it or not.

**Pull request merged**
