### PR TITLE
Add API endpoints

### PR DESCRIPTION
**Pull request by ryanmitchell**
Beginnings of endpoints - code should all work but docs are not yet complete.
If anyone else has time to jump in on the docs and complete them it would be helpful.

### CODE REVIEW

**Comment by ryanmitchell** [comment]
@sampoyigi Should be complete now

**Comment by sampoyigi** [comment]
I'm not sure about exposing the coupon history database, we want developers to add history using the logHistory method or something similar and not directly adding records to the DB table.. Also the history can be exposed as a relationship of coupons and history only added when there's an order to associate with it.

**Comment by ryanmitchell** [comment]
No problem. Happy to leave history out of it - I can see what you mean.

**Comment by sampoyigi** [comment]
Let me know if you're happy with the changes

**Comment by ryanmitchell** [comment]
Yep all good, thanks.

**Pull request merged**
